version: '3.1'

services:

  database:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: xwrqavrtyqrhgsre
      MARIADB_DATABASE: immo
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080